# Controls when the workflow will run
on:
  # Allows you to run this workflow manually ftarget the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_NAME: Checkers playdate Html
  

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Grab FFMPEG
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          
      - name: Checkout Playdate SDL2 Api Sources
        uses: actions/checkout@v3
        with:
          repository: 'joyrider3774/Playdate_Api_SDL2'

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          path: tmp
        
      - name: Checkout EMSDK sources
        uses: actions/checkout@v3
        with:
          path: emsdk
          repository: 'emscripten-core/emsdk'

      - name: Setup EMSDK stuff
        run: |
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest            
       
      - name: move things to correct directories
        run: |
          rm -rf ./src/srcgame
          mv tmp/src ./src/srcgame
          cp -Rf tmp/Source/. ./Source

      - name: Build Game        
        run: |
          source ./emsdk/emsdk_env.sh
          emmake make CPP_BUILD=1 EMSCRIPTEN_BUILD=1 EMSCRIPTEN_ASYNCIFY=1 WINDOWSCALE=2 SCREENRESX=320 SCREENRESY=240

      - name: Store build
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: html
